// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/rode/es-index-manager/indexmanager"
)

type FakeMappingsRegistry struct {
	AliasNameStub        func(string, string) string
	aliasNameMutex       sync.RWMutex
	aliasNameArgsForCall []struct {
		arg1 string
		arg2 string
	}
	aliasNameReturns struct {
		result1 string
	}
	aliasNameReturnsOnCall map[int]struct {
		result1 string
	}
	IndexNameStub        func(string, string) string
	indexNameMutex       sync.RWMutex
	indexNameArgsForCall []struct {
		arg1 string
		arg2 string
	}
	indexNameReturns struct {
		result1 string
	}
	indexNameReturnsOnCall map[int]struct {
		result1 string
	}
	LoadMappingsStub        func() error
	loadMappingsMutex       sync.RWMutex
	loadMappingsArgsForCall []struct {
	}
	loadMappingsReturns struct {
		result1 error
	}
	loadMappingsReturnsOnCall map[int]struct {
		result1 error
	}
	MappingStub        func(string) *indexmanager.VersionedMapping
	mappingMutex       sync.RWMutex
	mappingArgsForCall []struct {
		arg1 string
	}
	mappingReturns struct {
		result1 *indexmanager.VersionedMapping
	}
	mappingReturnsOnCall map[int]struct {
		result1 *indexmanager.VersionedMapping
	}
	VersionStub        func(string) string
	versionMutex       sync.RWMutex
	versionArgsForCall []struct {
		arg1 string
	}
	versionReturns struct {
		result1 string
	}
	versionReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMappingsRegistry) AliasName(arg1 string, arg2 string) string {
	fake.aliasNameMutex.Lock()
	ret, specificReturn := fake.aliasNameReturnsOnCall[len(fake.aliasNameArgsForCall)]
	fake.aliasNameArgsForCall = append(fake.aliasNameArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.AliasNameStub
	fakeReturns := fake.aliasNameReturns
	fake.recordInvocation("AliasName", []interface{}{arg1, arg2})
	fake.aliasNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMappingsRegistry) AliasNameCallCount() int {
	fake.aliasNameMutex.RLock()
	defer fake.aliasNameMutex.RUnlock()
	return len(fake.aliasNameArgsForCall)
}

func (fake *FakeMappingsRegistry) AliasNameCalls(stub func(string, string) string) {
	fake.aliasNameMutex.Lock()
	defer fake.aliasNameMutex.Unlock()
	fake.AliasNameStub = stub
}

func (fake *FakeMappingsRegistry) AliasNameArgsForCall(i int) (string, string) {
	fake.aliasNameMutex.RLock()
	defer fake.aliasNameMutex.RUnlock()
	argsForCall := fake.aliasNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMappingsRegistry) AliasNameReturns(result1 string) {
	fake.aliasNameMutex.Lock()
	defer fake.aliasNameMutex.Unlock()
	fake.AliasNameStub = nil
	fake.aliasNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeMappingsRegistry) AliasNameReturnsOnCall(i int, result1 string) {
	fake.aliasNameMutex.Lock()
	defer fake.aliasNameMutex.Unlock()
	fake.AliasNameStub = nil
	if fake.aliasNameReturnsOnCall == nil {
		fake.aliasNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.aliasNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeMappingsRegistry) IndexName(arg1 string, arg2 string) string {
	fake.indexNameMutex.Lock()
	ret, specificReturn := fake.indexNameReturnsOnCall[len(fake.indexNameArgsForCall)]
	fake.indexNameArgsForCall = append(fake.indexNameArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.IndexNameStub
	fakeReturns := fake.indexNameReturns
	fake.recordInvocation("IndexName", []interface{}{arg1, arg2})
	fake.indexNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMappingsRegistry) IndexNameCallCount() int {
	fake.indexNameMutex.RLock()
	defer fake.indexNameMutex.RUnlock()
	return len(fake.indexNameArgsForCall)
}

func (fake *FakeMappingsRegistry) IndexNameCalls(stub func(string, string) string) {
	fake.indexNameMutex.Lock()
	defer fake.indexNameMutex.Unlock()
	fake.IndexNameStub = stub
}

func (fake *FakeMappingsRegistry) IndexNameArgsForCall(i int) (string, string) {
	fake.indexNameMutex.RLock()
	defer fake.indexNameMutex.RUnlock()
	argsForCall := fake.indexNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMappingsRegistry) IndexNameReturns(result1 string) {
	fake.indexNameMutex.Lock()
	defer fake.indexNameMutex.Unlock()
	fake.IndexNameStub = nil
	fake.indexNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeMappingsRegistry) IndexNameReturnsOnCall(i int, result1 string) {
	fake.indexNameMutex.Lock()
	defer fake.indexNameMutex.Unlock()
	fake.IndexNameStub = nil
	if fake.indexNameReturnsOnCall == nil {
		fake.indexNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.indexNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeMappingsRegistry) LoadMappings() error {
	fake.loadMappingsMutex.Lock()
	ret, specificReturn := fake.loadMappingsReturnsOnCall[len(fake.loadMappingsArgsForCall)]
	fake.loadMappingsArgsForCall = append(fake.loadMappingsArgsForCall, struct {
	}{})
	stub := fake.LoadMappingsStub
	fakeReturns := fake.loadMappingsReturns
	fake.recordInvocation("LoadMappings", []interface{}{})
	fake.loadMappingsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMappingsRegistry) LoadMappingsCallCount() int {
	fake.loadMappingsMutex.RLock()
	defer fake.loadMappingsMutex.RUnlock()
	return len(fake.loadMappingsArgsForCall)
}

func (fake *FakeMappingsRegistry) LoadMappingsCalls(stub func() error) {
	fake.loadMappingsMutex.Lock()
	defer fake.loadMappingsMutex.Unlock()
	fake.LoadMappingsStub = stub
}

func (fake *FakeMappingsRegistry) LoadMappingsReturns(result1 error) {
	fake.loadMappingsMutex.Lock()
	defer fake.loadMappingsMutex.Unlock()
	fake.LoadMappingsStub = nil
	fake.loadMappingsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMappingsRegistry) LoadMappingsReturnsOnCall(i int, result1 error) {
	fake.loadMappingsMutex.Lock()
	defer fake.loadMappingsMutex.Unlock()
	fake.LoadMappingsStub = nil
	if fake.loadMappingsReturnsOnCall == nil {
		fake.loadMappingsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.loadMappingsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMappingsRegistry) Mapping(arg1 string) *indexmanager.VersionedMapping {
	fake.mappingMutex.Lock()
	ret, specificReturn := fake.mappingReturnsOnCall[len(fake.mappingArgsForCall)]
	fake.mappingArgsForCall = append(fake.mappingArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.MappingStub
	fakeReturns := fake.mappingReturns
	fake.recordInvocation("Mapping", []interface{}{arg1})
	fake.mappingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMappingsRegistry) MappingCallCount() int {
	fake.mappingMutex.RLock()
	defer fake.mappingMutex.RUnlock()
	return len(fake.mappingArgsForCall)
}

func (fake *FakeMappingsRegistry) MappingCalls(stub func(string) *indexmanager.VersionedMapping) {
	fake.mappingMutex.Lock()
	defer fake.mappingMutex.Unlock()
	fake.MappingStub = stub
}

func (fake *FakeMappingsRegistry) MappingArgsForCall(i int) string {
	fake.mappingMutex.RLock()
	defer fake.mappingMutex.RUnlock()
	argsForCall := fake.mappingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMappingsRegistry) MappingReturns(result1 *indexmanager.VersionedMapping) {
	fake.mappingMutex.Lock()
	defer fake.mappingMutex.Unlock()
	fake.MappingStub = nil
	fake.mappingReturns = struct {
		result1 *indexmanager.VersionedMapping
	}{result1}
}

func (fake *FakeMappingsRegistry) MappingReturnsOnCall(i int, result1 *indexmanager.VersionedMapping) {
	fake.mappingMutex.Lock()
	defer fake.mappingMutex.Unlock()
	fake.MappingStub = nil
	if fake.mappingReturnsOnCall == nil {
		fake.mappingReturnsOnCall = make(map[int]struct {
			result1 *indexmanager.VersionedMapping
		})
	}
	fake.mappingReturnsOnCall[i] = struct {
		result1 *indexmanager.VersionedMapping
	}{result1}
}

func (fake *FakeMappingsRegistry) Version(arg1 string) string {
	fake.versionMutex.Lock()
	ret, specificReturn := fake.versionReturnsOnCall[len(fake.versionArgsForCall)]
	fake.versionArgsForCall = append(fake.versionArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.VersionStub
	fakeReturns := fake.versionReturns
	fake.recordInvocation("Version", []interface{}{arg1})
	fake.versionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMappingsRegistry) VersionCallCount() int {
	fake.versionMutex.RLock()
	defer fake.versionMutex.RUnlock()
	return len(fake.versionArgsForCall)
}

func (fake *FakeMappingsRegistry) VersionCalls(stub func(string) string) {
	fake.versionMutex.Lock()
	defer fake.versionMutex.Unlock()
	fake.VersionStub = stub
}

func (fake *FakeMappingsRegistry) VersionArgsForCall(i int) string {
	fake.versionMutex.RLock()
	defer fake.versionMutex.RUnlock()
	argsForCall := fake.versionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMappingsRegistry) VersionReturns(result1 string) {
	fake.versionMutex.Lock()
	defer fake.versionMutex.Unlock()
	fake.VersionStub = nil
	fake.versionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeMappingsRegistry) VersionReturnsOnCall(i int, result1 string) {
	fake.versionMutex.Lock()
	defer fake.versionMutex.Unlock()
	fake.VersionStub = nil
	if fake.versionReturnsOnCall == nil {
		fake.versionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.versionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeMappingsRegistry) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.aliasNameMutex.RLock()
	defer fake.aliasNameMutex.RUnlock()
	fake.indexNameMutex.RLock()
	defer fake.indexNameMutex.RUnlock()
	fake.loadMappingsMutex.RLock()
	defer fake.loadMappingsMutex.RUnlock()
	fake.mappingMutex.RLock()
	defer fake.mappingMutex.RUnlock()
	fake.versionMutex.RLock()
	defer fake.versionMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMappingsRegistry) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ indexmanager.MappingsRegistry = new(FakeMappingsRegistry)
